# Generated by Django 6.0.2 on 2026-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='category',
            field=models.CharField(choices=[('Silk', 'Silk'), ('Cotton', 'Cotton'), ('Bridal', 'Bridal'), ('Party', 'Party'), ('Designer', 'Designer')], default='Silk', max_length=50),
        ),
    ]
