# Generated by Django 6.0.2 on 2026-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_saree_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='sarees/'),
        ),
    ]
