# Generated by Django 6.0.2 on 2026-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_coupon_order_discount_amount_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='sarees/'),
        ),
        migrations.AddField(
            model_name='saree',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='sarees/'),
        ),
    ]
