# Generated by Django 6.0.2 on 2026-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_saree_image3_saree_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='occasion',
            field=models.CharField(blank=True, choices=[('', '— No Occasion —'), ('Wedding', 'Wedding'), ('Engagement', 'Engagement'), ('Mehendi', 'Mehendi'), ('Haldi', 'Haldi'), ('Reception', 'Reception'), ('Festival', 'Festival'), ('Party', 'Party'), ('Casual', 'Casual'), ('Office', 'Office')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='saree',
            name='category',
            field=models.CharField(choices=[('Saree', 'Saree'), ('Lehenga', 'Lehenga'), ('Salwar', 'Salwar Kameez'), ('Kurti', 'Kurti'), ('Anarkali', 'Anarkali')], default='Saree', max_length=50),
        ),
        migrations.AlterField(
            model_name='saree',
            name='fabric',
            field=models.CharField(choices=[('Kanchipuram Silk', 'Kanchipuram Silk'), ('Banarasi Silk', 'Banarasi Silk'), ('Chanderi Silk', 'Chanderi Silk'), ('Raw Silk', 'Raw Silk'), ('Georgette', 'Georgette'), ('Chiffon', 'Chiffon'), ('Cotton', 'Cotton'), ('Linen', 'Linen'), ('Organza', 'Organza'), ('Velvet', 'Velvet'), ('Net', 'Net'), ('Crepe', 'Crepe'), ('Tussar Silk', 'Tussar Silk'), ('Mysore Silk', 'Mysore Silk'), ('Patola Silk', 'Patola Silk'), ('Jamdani', 'Jamdani'), ('Pochampally', 'Pochampally'), ('Sambalpuri', 'Sambalpuri'), ('Bandhani', 'Bandhani'), ('Embroidered Net', 'Embroidered Net'), ('Tissue Silk', 'Tissue Silk'), ('Other', 'Other')], default='Kanchipuram Silk', max_length=100),
        ),
    ]
